# Generated by Django 4.0 on 2022-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_orderitem_cartitem_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='/images/no-image.jpg', upload_to='uploads/'),
        ),
    ]
