# Generated by Django 4.0 on 2022-01-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cartitem_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('Bs', 'BestSeller')], default='', max_length=2, null=True),
        ),
    ]
