# Generated by Django 4.0 on 2022-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
