# Generated by Django 4.0 on 2022-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_useraddress_card_no_useraddress_name_on_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='exp_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='exp_year',
            field=models.IntegerField(null=True),
        ),
    ]
