# Generated by Django 4.0 on 2022-01-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_useraddress_exp_date_useraddress_exp_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='Card_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='exp_month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='exp_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
