# Generated by Django 4.0 on 2022-01-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_useraddress_card_no_alter_useraddress_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
